# Generated by Django 5.0.4 on 2024-04-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jems_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='langue_preferee',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='role',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='statut_compte',
        ),
    ]
